const { OpenAI } = require("openai")
const { z } = require("zod")
const { zodResponseFormat } = require('openai/helpers/zod')
const puppeteer = require("puppeteer")

const openai = new OpenAI({
    baseURL: "https://integrate.api.nvidia.com/v1",

    apiKey: process.env.OPENAI_COMPATIBLE_API_KEY
})

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("The match score between the candidate and the job describe, i.e. how well the candidate matches the job describe"),

    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be ask in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("how to answer this question, what points to cover, what approach to take etc.")
    })).describe("Technical question that can be ask in the interview along with intention how to answer them"),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question can be ask in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("how to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behavioral question that can be ask in the interview along with intention how to answer them"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which the candidate is lacking"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap, i.e."),
    })).describe("The skill gaps that the candidate has along with severity"),
    preparationPlan: z.array(z.object({
            day: z.number().describe("The day number of the preparation plan, starting from 1"),
            focus: z.string().describe("The main foucs of this day in the preparation plan, i.e. what to focus on this day"),
            tasks: z.array(z.string()).describe("List of tasks to be done on this day in the preparation plan, i.e. what to do on this day")
        })).describe("A day wise preparation plan for candidate to follow in order to prepare for the interview"),
        title: z.string().describe("The title of the job for which the interview report is generated"),
    })

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const completion = await openai.chat.completions.create({
        model: "nvidia/nemotron-3-super-120b-a12b",
        messages: [
            {
                role: "system",
                content: "You are an expert technical recruiter and interview coach. Analyze the provided Candidate Resume, Self-Description, and Job Description thoroughly. Generate an accurate match score, realistic technical and behavioral interview questions with intentions and answers, pinpoint actual skill gaps based on the job requirements, and create a practical preparation plan."
            }, {
                role: "user",
                content: `Generate an interview report for a candidate with the following details: Resume: ${resume} Self - desciption: ${selfDescription} Job description: ${jobDescription}`
            }
        ],
        response_format: zodResponseFormat(interviewReportSchema, "interview_report"),

    })
    return JSON.parse(completion.choices[0].message.content);
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' })

    const pdfBuffer = await page.pdf({ format: 'A4', margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } })
    await browser.close()
    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
    const resumepdfSchema = z.object({
        html: z.string().describe("The html content of the resume report, which can be converted to PDF using puppeteer"),
    })

    const prompt = `Generate  resume  for a candidate with the following details: Resume details: ${resume} Self - describe: ${selfDescription} Job description: ${jobDescription}
    the response should be a JSON object with a single field "html" which contains of the resume which can be converted to PDF using puppeteer.
    The content of the resume should be not sound like it's generated by AI and should be close as possible to a real human-written resume.
    You can hightlight the content using some colors or different font styles but the overall design should be simple and professional.
    the content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
    The resume should not be so lengthy, it should be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all relevant information that can increase the candidate's chances of getting an interview call for the given job description.
    `
    const completion = await openai.chat.completions.create({
        model: "nvidia/nemotron-3-super-120b-a12b",
        messages: [
            {
                role: "system",
                content: "You are an expert resume writer. Create a professional resume based on the provided details."
            }, {
                role: "user",
                content: prompt
            }
        ],
        response_format: zodResponseFormat(resumepdfSchema, "resume_pdf"),
    })

    const jsonContent = JSON.parse(completion.choices[0].message.content);

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

module.exports = {generateInterviewReport, generateResumePdf}